apiVersion: v1
kind: Secret

metadata:
  name: chatbot-secret
  namespace: chatbot

type: Opaque

stringData:

  DB_USER: chatbot_user

  DB_PASSWORD: chatbot_password

  MYSQL_ROOT_PASSWORD: root_password
